In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('mpg.csv')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [5]:
df.shape
#398 satır 9 sütun

(398, 9)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [9]:
df['horsepower'].astype(int)
# burda soru işareti varmış o yüzden obje
#invalid literal for int() with base 10: '?'

ValueError: invalid literal for int() with base 10: '?'

In [10]:
df[df['horsepower']=='?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,?,2046,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl

In [12]:
df['horsepower'].replace('?',np.nan , inplace = True)
#soru işaretleri yerine nan koyduk

In [14]:
df['horsepower'].astype(int)
#float olan nan'ları int döndüremiyoruz.
# ValueError: cannot convert float NaN to integer

ValueError: cannot convert float NaN to integer

In [16]:
# df['horsepower'].astype(float)
# 1. yol

In [18]:
#2. yol
df['horsepower'] = df['horsepower'].dropna().astype(int)
# nanlar haricindekileri de int yapmak.

In [19]:
# mpg performansını yıllara göre kıyasla.

In [20]:
df.model_year.unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

In [21]:
df.model_year.value_counts()

model_year
73    40
78    36
76    34
82    31
75    30
80    29
79    29
81    29
70    29
71    28
72    28
77    28
74    27
Name: count, dtype: int64

# .groupby methodu

In [22]:
# .groupby(stün ismi) bu kullanım ile bir sütundaki değerleri göre gruplama yapılabilir.
# devamında aggregate function'ına bakmalıyız.

- mean(): mean of groups
- sum(): sum of  groups
- size(): group sizes
- count(): count of group
- std(): standart variance of groups
- var(): variance of groups
- sem(): standart error of the mean of groups
- describe(): generates descirptive statistics
- first(): first of group values
- last(): last of group values
- nth(): take mth value , or a subset if in is a list
- min(): min of group values
- max(): max of group values
### Full list online documentation:https://pandas.pydata.org/docs/reference/groupby.html

In [23]:
#soru mpg performansını yıllara göre kıyasla

In [26]:
df.groupby('model_year')['mpg'].mean()

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

In [27]:
# 80'li yıllara gelindiğinde muhtemelen arabaların daha hızlı gitmesine kaynaklı yakıt tüketimleri artmıştır.

In [39]:
df.groupby( by = ['model_year','displacement']).count()

                         mpg  cylinders  horsepower  weight  acceleration  \
model_year displacement
70         97.0            2          2           2       2             2
           104.0           1          1           1       1             1
           107.0           1          1           1       1             1
           110.0           1          1           1       1             1
           113.0           1          1           1       1             1
...                      ...        ...         ...     ...           ...
82         151.0           3          3           2       3             3
           156.0           1          1           1       1             1
           181.0           1          1           1       1             1
           232.0           1          1           1       1             1
           262.0           1          1           1       1             1

                         origin  name
model_year displacement
70         97.0               2     2
           104.0              1     1
           107.0              1     1
           110.0              1     1
           113.0              1     1
...                         ...   ...
82         151.0              3     3
           156.0              1     1
           181.0              1     1
           232.0              1     1
           262.0              1     1

[287 rows x 7 columns]

In [41]:
df.groupby('model_year').describe()

             mpg                                                          \
           count       mean       std   min     25%    50%     75%   max
model_year
70          29.0  17.689655  5.339231   9.0  14.000  16.00  22.000  27.0
71          28.0  21.250000  6.591942  12.0  15.500  19.00  27.000  35.0
72          28.0  18.714286  5.435529  11.0  13.750  18.50  23.000  28.0
73          40.0  17.100000  4.700245  11.0  13.000  16.00  20.000  29.0
74          27.0  22.703704  6.420010  13.0  16.000  24.00  27.000  32.0
75          30.0  20.266667  4.940566  13.0  16.000  19.50  23.000  33.0
76          34.0  21.573529  5.889297  13.0  16.750  21.00  26.375  33.0
77          28.0  23.375000  6.675862  15.0  17.375  21.75  30.000  36.0
78          36.0  24.061111  6.898044  16.2  19.350  20.70  28.000  43.1
79          29.0  25.093103  6.794217  15.5  19.200  23.90  31.800  37.3
80          29.0  33.696552  7.037983  19.1  29.800  32.70  38.100  46.6
81          29.0  30.334483  5.591465  17.6  26.600  31.60  34.400  39.1
82          31.0  31.709677  5.392548  22.0  27.000  32.00  36.000  44.0

           cylinders            ... acceleration       origin            \
               count      mean  ...          75%   max  count      mean
model_year                      ...
70              29.0  6.758621  ...       15.000  20.5   29.0  1.310345
71              28.0  5.571429  ...       16.125  20.5   28.0  1.428571
72              28.0  5.821429  ...       16.625  23.5   28.0  1.535714
73              40.0  6.375000  ...       16.000  21.0   40.0  1.375000
74              27.0  5.259259  ...       17.000  21.0   27.0  1.666667
75              30.0  5.600000  ...       17.375  21.0   30.0  1.466667
76              34.0  5.647059  ...       17.550  22.2   34.0  1.470588
77              28.0  5.464286  ...       16.925  19.0   28.0  1.571429
78              36.0  5.361111  ...       16.825  21.5   36.0  1.611111
79              29.0  5.827586  ...       17.300  24.8   29.0  1.275862
80              29.0  4.137931  ...       18.700  23.7   29.0  2.206897
81              29.0  4.620690  ...       17.300  20.7   29.0  1.965517
82              31.0  4.193548  ...       18.000  24.6   31.0  1.645161


                 std  min  25%  50%  75%  max
model_year
70          0.603765  1.0  1.0  1.0  1.0  3.0
71          0.741798  1.0  1.0  1.0  2.0  3.0
72          0.792658  1.0  1.0  1.0  2.0  3.0
73          0.667467  1.0  1.0  1.0  2.0  3.0
74          0.832050  1.0  1.0  1.0  2.0  3.0
75          0.730297  1.0  1.0  1.0  2.0  3.0
76          0.706476  1.0  1.0  1.0  2.0  3.0
77          0.835711  1.0  1.0  1.0  2.0  3.0
78          0.837608  1.0  1.0  1.0  2.0  3.0
79          0.591400  1.0  1.0  1.0  1.0  3.0
80          0.818505  1.0  2.0  2.0  3.0  3.0
81          0.944259  1.0  1.0  2.0  3.0  3.0
82          0.914636  1.0  1.0  1.0  3.0  3.0

[13 rows x 56 columns]

In [42]:
#.done