In [1]:
import numpy as np
import pandas as pd

In [2]:
simple_df = pd.DataFrame( data = [[1,2,2,2] , [1,2,3,4] , [1,2,2,2] , [1,2,2,2] ], index = ['a','b','c','d'] , columns = ['col1','col2','col3','col4'])
simple_df

   col1  col2  col3  col4
a     1     2     2     2
b     1     2     3     4
c     1     2     2     2
d     1     2     2     2

In [3]:
# duplicate veri genelde hatadan kaynaklanır
# birbirinin kopyası olan veri.

In [5]:
simple_df.duplicated()
# tekrar eden verileri true döndürür.

a    False
b    False
c     True
d     True
dtype: bool

In [10]:
simple_df.drop_duplicates()
#tekrar eden verileri burda düşürür.
#inplace parametresiyle kalıcı hale getirebiliriz.
# keep = last parametresiyle de c ve d yi alır sadece
# keep = false parametresiyle de tamamını düşürür.

   col1  col2  col3  col4
a     1     2     2     2
b     1     2     3     4

In [11]:
# amaç : total_bill değeri 10 ile 20 arasındaki satrıları getirmek.

In [14]:
df = pd.read_csv('tips.csv')

In [16]:
df[df['total_bill'].between(10,20)]
#default ayarlarda 10 ve 20 dahildir
#inculusive paramtersiyle left ve right ile 10 veya 20 'nin dahil olup olmayacağını seçebiliriz.

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786,Sun3775
10,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,566287581219,Sun2546
...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,Tracy Douglas,4097938155941930,Sat7220
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605,Sat4615
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [18]:
df.nlargest(5,'tip')
#tip sütununun en büyük 5 değerini getirir.

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025

In [20]:
df.nsmallest(5,'tip')
# tip stünunun en küçük 5 değerini getirir.

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959

In [21]:
#.done